apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditcard-service-deploy
  labels:
    app: creditcard-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : creditcard-service-app
  template:
    metadata:
      labels:
        app: creditcard-service-app
    spec:
      containers:
      - name: creditcard-service-app
        image: ethan2022/creditcard-service
        imagePullPolicy: Always
        ports:
          - containerPort: 9091

---

apiVersion: v1

kind: Service
metadata:
  name:  creditcard-service-app
spec:
  selector:
    app:  creditcard-service-app
  ports:
  - protocol: TCP
    port:  9091
    targetPort:  9091