apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app-deploy
  labels:
    app: gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway-app
          image: ethan2022/gateway-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8999

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8999
      targetPort: 8999
  