apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deploy
  labels:
    app: product-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
      - name: product-service-app
        image: ethan2022/product-service
        imagePullPolicy: Always
        ports:
          - containerPort: 9094
        env: # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf-prd  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf-prd
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password

---

apiVersion: v1

kind: Service
metadata:
  name:  product-service-svc
spec:
  selector:
    app:  product-service-app
  ports:
  - protocol: TCP
    port:  9094
    targetPort:  9094