apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: ethan2022/order-service
        imagePullPolicy: Always
        ports:
          - containerPort: 9095
        env: # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf-ord  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf-ord
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password


---

apiVersion: v1

kind: Service
metadata:
  name:  order-service-svc
spec:
  selector:
    app:  order-service-app
  ports:
  - protocol: TCP
    port:  9095
    targetPort:  9095