apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deploy
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-service-app
        image: ethan2022/account-service
        imagePullPolicy: Always
        ports:
          - containerPort: 9093
        env: # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf-acc  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf-acc
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password

---

apiVersion: v1
kind: Service
metadata:
  name:  user-service-svc
spec:
  selector:
    app:  user-service-app
  ports:
  - protocol: TCP
    port:  9093
    targetPort:  9093